name: flutter_falconx
description: A FalconX package project.
version: 4.0.0
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"

resolution: workspace

dependencies:
  app_links: ^7.2.1
  bloc_concurrency: ^0.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_falconnect:
    git:
      url: https://github.com/Nextzy/flutter-falconx
      ref: 4.0.0
      path: flutter_falconnect
  flutter_falmodel:
    git:
      url: https://github.com/Nextzy/flutter-falconx
      ref: 4.0.0
      path: flutter_falmodel
  flutter_falstore:
    git:
      url: https://github.com/Nextzy/flutter-falconx
      ref: 4.0.0
      path: flutter_falstore
  flutter_faltool:
    git:
      url: https://github.com/Nextzy/flutter-falconx
      ref: 4.0.0
      path: flutter_faltool
  flutter_local_notifications: ^22.3.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0
  yaml: ^3.1.4
