name: flutter_falstore
description: A secure storage solution for Flutter applications with comprehensive error handling and batch operations.
version: 4.0.1
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_faltool:
    git:
      url: https://github.com/Nextzy/flutter-falconx
      ref: 4.0.1
      path: flutter_faltool

  # PLATFORM: All
  flutter_secure_storage: ^11.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0
